services:
  - type: web
    name: beyond-survival-portal
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: daphne -b 0.0.0.0 -p $PORT wellness.asgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: bsr-database
          property: connectionString

databases:
  - name: bsr-database
    plan: free
