# Generated by Django 5.2.14 on 2026-05-19 07:12

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appuser",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
