# Generated by Django 5.2.14 on 2026-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0002_alter_appuser_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("members_count", models.IntegerField(default=0)),
                (
                    "icon_name",
                    models.CharField(
                        help_text="Material Icon name (e.g., 'groups')", max_length=50
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
    ]
