# Generated by Django 5.2.14 on 2026-05-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_gratitudethought"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportgroup",
            name="icon_name",
            field=models.CharField(
                help_text="Emoji or Material Icon descriptor name (e.g., '✨', '🌱', '🤝')",
                max_length=50,
            ),
        ),
    ]
