# Generated by Django 5.2.14 on 2026-05-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_alter_supportgroup_icon_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailySanctuaryContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_number",
                    models.PositiveIntegerField(
                        help_text="Day of the month (1 to 30) for this specific content set.",
                        unique=True,
                    ),
                ),
                (
                    "divine_guidance",
                    models.TextField(
                        help_text="Scripture text & peace message loaded by admin."
                    ),
                ),
                (
                    "daily_affirmation",
                    models.TextField(
                        help_text="The 'Sis, You Are...' affirmation text."
                    ),
                ),
                ("wellness_tip", models.TextField(help_text="Nourish wellness tip.")),
                (
                    "gratitude_prompt",
                    models.TextField(
                        help_text="Today's prompt for the reflection journal."
                    ),
                ),
                (
                    "daily_intention",
                    models.TextField(help_text="The 'Today I Choose...' text."),
                ),
            ],
            options={
                "verbose_name": "Daily Sanctuary Content",
                "verbose_name_plural": "Daily Sanctuary Content Calendar",
                "ordering": ["day_number"],
            },
        ),
        migrations.AlterField(
            model_name="appuser",
            name="wants_notifications",
            field=models.BooleanField(
                default=False,
                help_text="True if the user opts in to receive daily reminder emails.",
            ),
        ),
    ]
