# Generated by Django 5.2.14 on 2026-09-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0007_populate_sanctuary_calendar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportgroup",
            name="icon_name",
        ),
        migrations.RemoveField(
            model_name="supportgroup",
            name="members_count",
        ),
        migrations.AddField(
            model_name="supportgroup",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Web address if available",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="supportgroup",
            name="phone_number",
            field=models.CharField(
                blank=True,
                help_text="Phone number if available",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="supportgroup",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
