"""
Django settings for wellness project.

Generated by 'django-admin startproject' using Django 5.0.1.
"""

import os
from pathlib import Path

import dj_database_url  # Dynamically connects PostgreSQL on Render
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ
env = environ.Env(
    # Set casting defaults
    DEBUG=(bool, False)
)

# Read the .env file from the root directory
environ.Env.read_env(os.path.join(BASE_DIR, ".env"))

# --- Environment Configurations ---
SECRET_KEY = env(
    "SECRET_KEY",
    default="django-insecure-kzz+c7rs5%=+a^=-^or#8#n@#(we19803w(7!=5-q9zq(=7kt$",
)
DEBUG = env("DEBUG", default=True)

# Allow local testing and Render hostnames dynamically
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# THE FIX: Tell Django to trust secure form submissions coming from your Render domain
CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]


# --- Application Definition ---
INSTALLED_APPS = [
    "daphne",  # ASGI application server must be at the top
    "channels",  # Handles real-time WebSockets
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_countries",
    "main_app.apps.MainAppConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Optimizes serving CSS/JS on Render
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "wellness.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# Gateway Execution Routing Profiles
WSGI_APPLICATION = "wellness.wsgi.application"
ASGI_APPLICATION = "wellness.asgi.application"


# --- Databases ---
# Uses Render's secure PostgreSQL link when deployed, falls back to SQLite locally
if os.environ.get("DATABASE_URL"):
    DATABASES = {"default": dj_database_url.config(conn_max_age=600, ssl_require=True)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# --- Cache System ---
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "LOCATION": "unique-snowflake",
    }
}


# --- Password Validation ---
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# --- Internationalization ---
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# --- Static Files Configuration ---
STATIC_URL = "static/"
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]
# The absolute path where collectstatic will gather assets for production deployment
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")


# --- Custom User Model Identity Profile ---
AUTH_USER_MODEL = "main_app.AppUser"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
LOGIN_URL = "login"


# --- Core Secrets Configuration ---
GEMINI_API_KEY = env("GEMINI_API_KEY", default="")


# --- Email Configuration (Isolated gracefully across view parameters) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "Hallrozana39@gmail.com"
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD", default="")
DEFAULT_FROM_EMAIL = "Beyond Survival Sisterhood <Hallrozana39@gmail.com>"
